newrelic/newrelic-telemetry-sdk-dotnet

azure-pipelines.yml, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/ASPNetFrameworkApiApplication.csproj, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/App_Start/WebApiConfig.cs, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Controllers/WeatherForecastController.cs, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Global.asax, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Global.asax.cs, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Models/WeatherForecast.cs, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Properties/AssemblyInfo.cs, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/Web.config, src/NewRelic.Telemetry.Samples/ASPNetFrameworkApiApplication/packages.config, src/NewRelic.Telemetry.sln, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/App_Start/WebApiConfig.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Controllers/WeatherForecastController.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Global.asax, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Global.asax.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Models/WeatherForecast.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Properties/AssemblyInfo.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/SampleAspNetFrameworkApp.csproj, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Web.Debug.config, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Web.Release.config, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Web.config, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/packages.config
Add back ASPNetFrameworkApiApplication and SampleAspNetFrameworkApp.
Fix azure-pipelines.yml to build .Net framework apps.
Test build succeeded:
=> Dotnet 4468 add back fx sample apps

src/NewRelic.Telemetry.Samples/ConsoleApplicationWithTracer/SimpleTracer.cs, src/NewRelic.Telemetry.Tests/DataSenderTests.cs, src/NewRelic.Telemetry.Tests/SpanDataSenderTests.cs, src/NewRelic.Telemetry/Spans/README.md, src/NewRelic.Telemetry/TelemetryConfiguration.cs, src/OpenTelemetry.Exporter.NewRelic.Tests/SpanConverterTests.cs, src/OpenTelemetry.Exporter.NewRelic/NewRelicOpenTelemetryExtensions.cs
* Renamed `APIKey`->`ApiKey`
* Renamed `OverrideEndpointUrl_Trace` -> `OverrideEndpointUrlTrace`
=> DOTNET-4483 - Rename Identifiers

src/NewRelic.Telemetry.Tests/DataSenderTests.cs, src/NewRelic.Telemetry/Transport/DataSender.cs
Test DateSpecificRetry_CorrectDelayDuration(), line 37 was using .Now to set the future retry date. 
I suspect the server running the test is in a different timezone, and DateTimeOffset includes the timezone offset.
Test DelayRetry_DurationCorrect() was a duplicate of RetryOn429_429HappensOnce(). Removed.
Replaced DateSpecificRetry_CorrectDelayDuration() with RetryOn429WithSpecificDate_429HappensOnce(), using UtcNow, and refactoring to only retry once. Eliminated Asserts on values returned from the mocked HttpHandlerImpl.
Changed delay parameter to a uint, since it should always be positive.
=> fixed test (Now vs UtcNow), consolidated, made delay a uint

src/NewRelic.Telemetry.Tests/MetricBatchJsonTests.cs, src/NewRelic.Telemetry.Tests/MetricBatchTests.cs, src/NewRelic.Telemetry.Tests/MetricDataSenderTests.cs, src/NewRelic.Telemetry.Tests/MetricTests.cs, src/NewRelic.Telemetry/Metrics/Metric.cs
* Adds Create to MetricSummaryValue supporting two use cases, removing constructor
* Makes Native Value get public, adds ignore for Json serialization
* Updates tests accordingly
=> Small Revisions

src/OpenTelemetry.Exporter.NewRelic/NewRelicTraceExporter.cs
User-agent string for the exporter is [spec'd ](https://github.com/newrelic/newrelic-exporter-specs/blob/master/Common.md#user-agent-values)to be `NewRelic-Dotnet-OpenTelemetry/<version>`.
Note: This PR does not change the name of the NuGet package, however, now the NuGet package name and User-Agent in the Http header are different, whereas they were the same.
=> change user-agent string for exporter

src/NewRelic.Telemetry.Tests/SpanDataSenderTests.cs, src/NewRelic.Telemetry.Tests/SpanTests.cs, src/NewRelic.Telemetry/Spans/SpanBuilder.cs, src/NewRelic.Telemetry/Spans/SpanDataSender.cs, src/NewRelic.Telemetry/TelemetryConfiguration.cs, src/NewRelic.Telemetry/Transport/DataSender.cs, src/OpenTelemetry.Exporter.NewRelic.Tests/SpanConverterTests.cs, src/OpenTelemetry.Exporter.NewRelic/NewRelicTraceExporter.cs
**Instrumentation Provider**
* Adds Instrumentation Provider to TelemetryConfiguration
* Telemetry SDK sets "instrumentation.provider" attribute when the instrumentation provider config setting has a value
* OpenTelemetry Provider sets the Instrumentation Provider setting to "opentelemetry"
* Open Question:   Should the base TelemetrySDK set the config value to "dotnetTelemetrySDK".
**Error**
* Adds ability for TelemetrySDK user to supply HasError with a message string.  Sets HasError = true and sets the message.
* OpenTelemetry Status.Description value will be sent if status != Status.OK as the error message
* Modified tests to set a description
=> Instrumentation Provider and Error Messaging

README.md
This is from Zach Elwood on NR docs team. 
This PR is to add a ‘how to find data’ section so that customers can find the data they send. I’ve included what I think are the applicable data types (spans and metrics) but let me know if there are other data types reported by this exporter. If you think this exporter will change to send other types of data in future, keep in mind it will be important to update this repo with link to that data type.
Also changed some instances of title case to sentence case; small thing but we want headings to be sentence case and not title case, so just something to keep in mind when creating new content. Let me know if you think I changed sentence case stuff that shouldn't have been changed.
=> 'find and use data' section from docs team

azure-pipelines.yml
Excluding SonarCloud analysis from PR builds. It does not seem that it can be done from externally submitted PRs. I think this is a relevant feature request: https://jira.sonarsource.com/browse/MMF-1371.
Side note: We keep copy/pasting the same condition all over the `azure-pipeline.yml` file. Makes me think we need to explore different pipelines for different purposes, or maybe there's a different solution? ... Punting on this for now.
=> Perform SonarCloud analysis only on builds from master

src/IntegrationTests/Applications/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj, src/IntegrationTests/Applications/SampleAspNetCoreApp/Startup.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetCoreApp/SampleAspNetCoreApp.csproj, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetCoreApp/Startup.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/Global.asax.cs, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/SampleAspNetFrameworkApp.csproj, src/OpenTelemetry.Exporter.NewRelic.Samples/SampleAspNetFrameworkApp/packages.config, src/OpenTelemetry.Exporter.NewRelic.Tests/OpenTelemetry.Exporter.NewRelic.Tests.csproj, src/OpenTelemetry.Exporter.NewRelic.Tests/SpanConverterTests.cs, src/OpenTelemetry.Exporter.NewRelic/NewRelicTraceExporter.cs, src/OpenTelemetry.Exporter.NewRelic/OpenTelemetry.Exporter.NewRelic.csproj
0.2.0-alpha.179 is the currently published version of OpenTelemetry nuget packages.
Changes that impacted us were mostly made in this PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/420. Great discussion in that PR describing the theory behind the changes.
More breaking changes likely in the next version pushed to nuget. I'll evaluate this.
=> Update exporter to use OpenTelemetry 0.2.0-alpha.179

src/OpenTelemetry.Exporter.NewRelic/README.md
Addresses #91.
Simplifies the README for the exporter to reduce confusion - namely, directing users to review the example applications for usage details. This also reduces the maintenance overhead as the API evolves.
=> Clean up exporter readme

.github/workflows/main.yml
Resolves #105 
Adds a workflow for buildings and deploying the TelemetrySDK and Exporter.
- Restores solution
- Builds solution
- Run unit tests
- Can deploy
- Saves the build artifacts, though we are still working out what to do with them or if this is the best method of saving them.
Notes: 
- Builds of master or adding a formatted tag will trigger a release as in the pipelines.
=> Initial main.yml workflow.

NewRelic.sln, examples/OpenTelemetry.Exporter.NewRelic/ConsoleCore/NewRelic.Examples.ConsoleCore.csproj, examples/OpenTelemetry.Exporter.NewRelic/ConsoleCore/Program.cs
Resolves #140 by adding a `netcoreapp3.0` console application which demonstrates using our OpenTelemetry exporter to send a simple OpenTelemetry trace to New Relic, provided an appropriate API key.
=> Add sample console app

src/NewRelic.OpenTelemetry/NewRelicExporterHelperExtensions.cs, src/NewRelic.OpenTelemetry/NewRelicExporterOptions.cs, src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs, src/NewRelic.Telemetry/TelemetryConfiguration.cs, tests/NewRelic.OpenTelemetry.Tests/NewRelicExporterTests.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs
- Defines a smaller set of configuration options for the New Relic Open Telemetry Exporter.
- Makes the Telemetry SDK configuration internal, when used within the context of the Open Telemetry Exporter.
=> Creates New Relic Open Telemetry exporter configuration options.

examples/NewRelic.Telemetry/AspNet/Controllers/WeatherForecastController.cs, examples/NewRelic.Telemetry/AspNetCore/Controllers/WeatherForecastController.cs, examples/NewRelic.Telemetry/Console/Program.cs, src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs, src/NewRelic.Telemetry/NewRelicConsts.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs, tests/NewRelic.Telemetry.Tests/SpanBatchJsonTests.cs, tests/NewRelic.Telemetry.Tests/SpanBuilderTests.cs
The New Relic UI does not rely on the `error` attribute. Currently, it only relies on the presence of the `error.message` attribute to indicate that a span has an error.
=> Remove error attribute

src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs
The OpenTelemetry spec changed in regards to span status. Only three possible values for status: `Unset` (default), `Ok`, and `Error`. See: https://github.com/open-telemetry/opentelemetry-specification/blob/5c9143b031c078543c400412ab214c37cb9903ea/specification/trace/api.md#set-status.
From the spec:
> Generally, Instrumentation Libraries SHOULD NOT set the status code to Ok, unless explicitly configured to do so. Instrumention libraries SHOULD leave the status code as Unset unless there is an error, as described above.
This PR fixes an issue where spans with the status `Unset` would be rendered as an error in the New Relic UI.
This issue was originally reported by @twaremike https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/issues/140#issuecomment-713178515
=> Only set error.message when span.Status == StatusCode.Error

src/NewRelic.OpenTelemetry/NewRelicExporterOptions.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs
For the exporter the InstrumentationProvider is always equal to `opentelemetry`.
=> Remove InstrumentationProvider config setting

src/NewRelic.OpenTelemetry/NewRelicExporterOptions.cs, src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs, src/NewRelic.Telemetry/ITelemetryDataType.cs, src/NewRelic.Telemetry/Metrics/NewRelicMetricBatch.cs, src/NewRelic.Telemetry/Metrics/NewRelicMetricBatchCommonProperties.cs, src/NewRelic.Telemetry/NewRelicConsts.cs, src/NewRelic.Telemetry/Spans/NewRelicSpanBatch.cs, src/NewRelic.Telemetry/Spans/NewRelicSpanBatchCommonProperties.cs, src/NewRelic.Telemetry/TelemetryConfiguration.cs, src/NewRelic.Telemetry/Transport/DataSender.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs, tests/NewRelic.Telemetry.Tests/SpanDataSenderTests.cs
Removes InstrumentationProvider from TelemetryConfiguration since this is no longer part of the spec.
However, both `collector.name` and `instrumentation.provider` are expected to be on each batch of spans sent by the exporter. See https://github.com/newrelic/newrelic-exporter-specs/blob/61ebffa7d292c2085af612706f11d5b0a5108da9/opentelemetry/OpenTelemetry-Spans.md
=> Add collector.name to each span batch

src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs
`TagObjects` is a new collection as of System.Diagnostics.DiagnosticSource v5. It supports attributes with any arbitrary `object` value. The `Tags` collection is the legacy collection, it only supports string values, and it is not guaranteed to have any of the attributes added using the new `SetTag` API (vs. the legacy `AddTag` API... I know... confusing). OTel exclusively uses `SetTag`. This meant we were not sending up all the attributes.
=> Use TagObjects not Tags

src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs
A bug fixed in System.Diagnostics.DiagnosticSource RC2 required a more elaborate ParentSpanId check.
=> Simplify ParentSpanId check

.github/workflows/main.yml
Fixes the warnings/errors about using deprecated APIs with the github actions that we use by updating those dependencies.
=> Update deprecated GHA dependencies

tests/NewRelic.Telemetry.Tests/DataSenderTests.cs
Increases the error margin in the flickering test.
We should eventually replace this test with more of an end to end test where we actually verify that the retry occurred after waiting until the retry date.
=> Reduce test flicker

.github/workflows/main.yml, build/Common.prod.props
Updates the build flags and build commands so that we can generate Nuget packages that pass the Nuget Package Explorer health checks. 
This also keeps our build flags in line with the build flags used for the OpenTelemetry SDK that we depend on.
This does not change the behavior for the packages in MyGet. The packages pushed to MyGet will no longer pass the health checks.
See https://github.com/dotnet/sourcelink/blob/master/docs/README.md#deterministicsourcepaths for more information about the build flags that are being used.
=> Update build flags

examples/NewRelic.OpenTelemetry/ConsoleCore/NewRelic.Examples.ConsoleCore.csproj, examples/NewRelic.OpenTelemetry/ConsoleCore/Program.cs, examples/NewRelic.OpenTelemetry/ConsoleCore/appsettings.json
Responding to feedback from @twaremike in issue #140.  The arbitrary ten second sleep is not necessary.  The spans get exported when the exporter is shut down upon disposal, i.e. when the console app exits.
There is still an issue with the debug logging that prints out - depending on what shell you're running the program from, the output may or may not be completely displayed (for example, `git bash` always displays all of the debug logging, but it gets cut off in Cmd.exe and powershell (5.1, haven't tried powershell core (6.0+) yet)).  This is why I put the sleep in place in the first place, I wanted to make sure the debug output would be displayed.
(Update: the last commit makes this somewhat better by putting the tracing activity in a `using` scope which will trigger the disposal, and …
=> Remove sleep from console sample app

examples/NewRelic.OpenTelemetry/AspNetCore/Startup.cs, examples/NewRelic.OpenTelemetry/ConsoleCore/Program.cs, src/NewRelic.OpenTelemetry/Internal/NewRelicEventSource.cs, src/NewRelic.OpenTelemetry/Internal/SelfDiagnosticsLogger.cs, src/NewRelic.OpenTelemetry/NewRelic.OpenTelemetry.csproj, src/NewRelic.OpenTelemetry/NewRelicExporterHelperExtensions.cs, src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs, src/NewRelic.Telemetry/Logging/ITelemetryLogger.cs, src/NewRelic.Telemetry/Logging/TelemetryLogging.cs, src/NewRelic.Telemetry/Metrics/MetricDataSender.cs, src/NewRelic.Telemetry/Spans/TraceDataSender.cs, src/NewRelic.Telemetry/Transport/DataSender.cs, tests/NewRelic.OpenTelemetry.Tests/SpanConverterTests.cs
The New Relic OTel exporter should leverage the same logging mechanism as the OTel SDK and Zipkin exporter is using.
The Telemetry SDK should continue to leverage ILogger for its logging.
Readme updates will be made in a separate PR.
=> Leverage OTel logging for the exporter

examples/NewRelic.OpenTelemetry/AspNet/NewRelic.Examples.AspNet.csproj, examples/NewRelic.OpenTelemetry/AspNet/Web.config, examples/NewRelic.OpenTelemetry/AspNet/packages.config, examples/NewRelic.OpenTelemetry/AspNetCore/NewRelic.Examples.AspNetCore.csproj, examples/NewRelic.OpenTelemetry/AspNetCore/Properties/launchSettings.json, examples/NewRelic.OpenTelemetry/AspNetCore/Startup.cs, examples/NewRelic.OpenTelemetry/ConsoleCore/NewRelic.Examples.ConsoleCore.csproj, examples/NewRelic.Telemetry/AspNet/NewRelic.Examples.AspNet.csproj, examples/NewRelic.Telemetry/AspNet/Web.config, examples/NewRelic.Telemetry/AspNet/packages.config, examples/NewRelic.Telemetry/AspNetCore/NewRelic.Examples.AspNetCore.csproj, examples/NewRelic.Telemetry/Console/NewRelic.Examples.Console.csproj, tests/NewRelic.OpenTelemetry.Tests/NewRelic.OpenTelemetry.Tests.csproj, tests/NewRelic.OpenTelemetry.Tests/NewRelicExporterTests.cs, tests/NewRelic.Telemetry.Tests/DataSenderTests.cs, tests/NewRelic.Telemetry.Tests/MetricBatchJsonTests.cs, tests/NewRelic.Telemetry.Tests/NewRelic.Telemetry.Tests.csproj, tests/NewRelic.Telemetry.Tests/SpanBatchJsonTests.cs, tests/NewRelic.Telemetry.Tests/TestHelpers.cs
Fixes the following build warnings:
- Nullable references
- Obsolete target frameworks by upgrading to .net 5
- Newtonsoft downgrades by updating references and binding redirects
- System.Numerics.Vector bad hint path
=> Fix build warnings

tests/NewRelic.OpenTelemetry.Tests/NewRelic.OpenTelemetry.Tests.csproj, tests/NewRelic.Telemetry.Tests/MetricBatchJsonTests.cs, tests/NewRelic.Telemetry.Tests/NewRelic.Telemetry.Tests.csproj
Runs our tests against the same frameworks that the nuget packages target.
For now the Telemetry SDK tests do not run against net45 because they rely on System.Text.Json so they will run against net461 instead.
The tests github action should already run the tests against all of the target frameworks.
=> Test against more target frameworks

tests/NewRelic.OpenTelemetry.Tests/TestHttpServer.cs
When running the tests locally on a machine with multiple ports already in use, some of the tests that involve running a http listener on a port will fail to start that listener. Updating the random port range to 20000-40000 seems to make this problem less likely to occur.
=> Allow more retry attempts when creating a test listener

examples/NewRelic.OpenTelemetry/ConsoleCore/Program.cs, src/NewRelic.OpenTelemetry/NewRelicExporterOptions.cs, src/NewRelic.OpenTelemetry/README.md
Removing the `AuditLoggingEnabled` setting until the requirements for this functionality is better defined. It will be easier to add in similar functionality later than it will be to modify any existing behavior that things are depending on.
=> Remove AuditLoggingEnabled exporter setting

.github/workflows/deploy.yml
This adds a manually triggered workflow that allows us to conditionally push either or both of the OpenTelemetry and Telemetry SDK Nuget packages to Nuget.
For whatever reason pushing the packages to Myget causes the packages to fail these validation checks, so pushing the packages to Nuget via Myget will cause our packages pulled from Nuget to fail these validations too. Adding this deployment workflow allows our Nuget packages to continue to pass the Nuget Package Explorer validation checks.
=> Add github workflow to push to Nuget

.github/workflows/deploy.yml
Use the Nuget V3 source so that symbols packages can be pushed automatically.
=> Update nuget source in deploy.yml

src/NewRelic.OpenTelemetry/NewRelicExporterOptions.cs, src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs
At the moment users can add NewRelic exporter through the `NewRelicExporterHelperExtensions.AddNewRelicExporter` method only. Since NewRelicExporterOptions and NewRelicTraceExporter classes couldn't be initialized outside the assembly.
Propose to make them public. This way user can save the reference to the processor somewhere and use the processor's public API. For example, method `ForceFlush`.
I noticed how it was done in the default exporters — [Jaeger](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.Jaeger) and [Zipkin](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.Zipkin) exporters are public.
=> Weak access modifiers for NewRelicExporterOptions and NewRelicTraceExporter

README.md
To indicate to the community that the repo is in the process of archival.  All other agents have either archived or added a note to indicate that intention.
=> Change readme to indicate in process of archiving
